user:
  name:
    length: 50
  email:
    length: 50
    case_sensitive: false
  password:
    length: 6
  gravatar:
    size: 80
    all_size: 50
  per_page: 10

session:
  params: "1"

reset_password:
  expired: 2
max_length: 140
picture_size: 5
resize_limit: [400, 400]
content_length: 80
